debugVectors = False

SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800
SCREEN_BUFFER = 50

NUM_SHIPS = 2
NUM_WAVES = 3

ASTEROID_POINTS     = 20
BIG_ALIEN_POINTS    = 100
SMALL_ALIEN_POINTS  = 250
WAVE_COMP_POINTS    = 1000
CANNON_COST           = 1
TORPEDO_COST          = 10
TANKER_DESTROYED_COST = 100

OBJECT_TYPE_NONE      = 0
OBJECT_TYPE_SHIP      = 1
OBJECT_TYPE_ALIEN     = 2
OBJECT_TYPE_TANKER    = 3
OBJECT_TYPE_ASTEROID  = 4
OBJECT_TYPE_CANNON    = 5
OBJECT_TYPE_AL_CANNON = 6
OBJECT_TYPE_TORPEDO   = 7
OBJECT_TYPE_T_CANNON  = 8
OBJECT_TYPE_BH        = 9

PI = 3.14159
TAU = 2 * PI
EFFECTIVE_ZERO = .00001

CANNON_MASS = 10.0
TORPEDO_MASS = 50.0
SMALL_ALIEN_MASS = 75.0
BIG_ALIEN_MASS = 200.0
ASTEROID_MASS = 10.0 # * radius. Should be r^2, but less inertia is fun.
IRON_ASTEROID_MASS = 20.0
SHIP_MASS = 100
BH_MASS = 50.0 # * radius

THRUST_LOW = .01 # adjust based on FPS, etc.
THRUST_MED = THRUST_LOW * 2
THRUST_HI  = THRUST_LOW * 3
THRUST_MAX = THRUST_LOW * 8

MAX_SPIN = .3
SPIN_DELTA = .025
MIN_ASTEROID_RADIUS = 10
SMALL_IMPULSE = 5 # How hard we can hit and survive

OBJECT_DIST_FAR  = SCREEN_WIDTH / 3
OBJECT_DIST_MED  = SCREEN_WIDTH / 6
OBJECT_DIST_NEAR = SCREEN_WIDTH / 20

SPEED_SLOW  = 1.0
SPEED_MED   = 1.5
SPEED_HI    = 4.0
SPEED_VHI   = 8.0


EVENT_DISPLAY_COUNT = 100

ATTACK_INIT  = 1
ATTACK_ALIGN = 2

TX_RESOURCE_FUEL = 1 << 0
TX_RESOURCE_ROUNDS = 1 << 1
TX_RESOURCE_TORPEDOS = 1 << 2
TX_RESOURCE_ALL = 0x7

TORPEDO_DELAY = 50 # lots of particles, need to limit how fast we send these

