SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800
SCREEN_BUFFER = 50

NUM_SHIPS = 3

SMALL_ALIEN_POINTS = 50
BIG_ALIEN_POINTS = 20
ASTEROID_POINTS = 5

OBJECT_TYPE_NONE = 0
OBJECT_TYPE_SHIP = 1
OBJECT_TYPE_ALIEN = 2
OBJECT_TYPE_ASTEROID = 3
OBJECT_TYPE_CANNON = 4
OBJECT_TYPE_TANKER = 5

PI = 3.14159
TAU = 2 * PI
EFFECTIVE_ZERO = .00001

THRUST_LOW = .01 # adjust based on FPS, etc.
THRUST_MED = THRUST_LOW * 2
THRUST_HI  = THRUST_LOW * 3
THRUST_MAX = THRUST_LOW * 8

MAX_SPIN = .3
SPIN_DELTA = .025

HEUR_GOTO   = 1
HEUR_WAIT   = 2
HEUR_ATTACK = 3

OBJECT_DIST_FAR  = 300
OBJECT_DIST_MED  = 150
OBJECT_DIST_NEAR = 50

SPEED_SLOW = 1
SPEED_MED = 2
SPEED_FAST = 4


